import { useEffect } from 'react';
import { useLocation } from 'wouter';

interface SeoConfig {
  title: string;
  description: string;
  keywords?: string;
}

const SEO_MAP: Record<string, SeoConfig> = {
  '/': {
    title: 'Nexa Traders | AI-Powered Crypto Arbitrage & High-Yield Trading Platform',
    description: 'Maximize your crypto growth with Nexa Traders. Our advanced AI arbitrage bot executes sub-second trades across top global exchanges for consistent daily returns.',
    keywords: 'crypto arbitrage, AI trading bot, automated crypto trading, bitcoin arbitrage, usdt earnings, nexa traders',
  },
  '/trades': {
    title: 'Live AI Trades & Telemetry | Nexa Traders',
    description: 'Monitor real-time crypto arbitrage trades, execution latency, venue spreads, and daily automated yield generated by Nexa Traders AI bots.',
    keywords: 'live crypto trades, arbitrage telemetry, trading bot metrics, crypto spread trading',
  },
  '/packages': {
    title: 'AI Arbitrage Trading Packages & Plans | Nexa Traders',
    description: 'Explore Nexa Traders AI arbitrage plans tailored for every investor. Automated daily profit payouts, flexible capital options, and transparent yields.',
    keywords: 'crypto investment plans, AI arbitrage packages, daily crypto yield, automated trading packages',
  },
  '/dashboard': {
    title: 'User Dashboard & Wallet | Nexa Traders',
    description: 'Manage your active Nexa Traders arbitrage packages, track daily profit payouts, deposit funds via USDT BEP20, and request instant withdrawals.',
    keywords: 'crypto dashboard, user portal, usdt deposit, crypto withdrawal, trading profits',
  },
  '/about': {
    title: 'About Nexa Traders | Advanced AI Arbitrage Trading Solutions',
    description: 'Learn how Nexa Traders leverages machine learning and flash arbitrage algorithms to deliver low-risk, high-frequency cryptocurrency trading yield.',
    keywords: 'about nexa traders, AI trading technology, quantitative crypto trading, flash arbitrage',
  },
  '/contact': {
    title: 'Contact Us & 24/7 Support | Nexa Traders',
    description: 'Have questions or need assistance? Reach out to the Nexa Traders support team for help with accounts, deposits, withdrawals, and trading packages.',
    keywords: 'nexa traders support, contact crypto platform, trading help, customer service',
  },
  '/privacy': {
    title: 'Privacy Policy & Data Security | Nexa Traders',
    description: 'Read the official Nexa Traders privacy policy to understand how we protect user data, secure financial transactions, and maintain account safety.',
    keywords: 'privacy policy, data protection, crypto platform security, terms of service',
  },
  '/login': {
    title: 'Sign In to Your Account | Nexa Traders',
    description: 'Sign in to Nexa Traders user dashboard to access your automated AI arbitrage trading portfolio and profit tracking.',
    keywords: 'login nexa traders, sign in crypto dashboard, user login',
  },
  '/register': {
    title: 'Create Free Account | Nexa Traders',
    description: 'Register for a free Nexa Traders account today and start earning daily automated returns with AI-driven crypto arbitrage trading.',
    keywords: 'register nexa traders, create account, sign up crypto trading',
  },
  '/admin/login': {
    title: 'Admin Portal Login | Nexa Traders',
    description: 'Secure admin authentication portal for Nexa Traders operational management.',
    keywords: 'admin login, nexa traders admin',
  },
  '/admin': {
    title: 'Admin Dashboard | Nexa Traders',
    description: 'Nexa Traders System Management, User Approvals, Withdrawal Requests, and Telemetry Control.',
    keywords: 'admin portal, system management',
  },
};

export function SeoHead() {
  const [location] = useLocation();

  useEffect(() => {
    const currentPath = location.split('?')[0].split('#')[0];
    const seo = SEO_MAP[currentPath] || {
      title: 'Nexa Traders | AI-Powered Crypto Arbitrage Trading Platform',
      description: 'Nexa Traders provides high-yield AI cryptocurrency arbitrage trading algorithms across global exchanges.',
      keywords: 'nexa traders, crypto arbitrage, automated trading',
    };

    // Update Page Title
    document.title = seo.title;

    // Helper function to safely update or append meta elements
    const setMetaTag = (selector: string, attrName: string, attrVal: string, content: string) => {
      let el = document.querySelector(selector);
      if (!el) {
        el = document.createElement('meta');
        el.setAttribute(attrName, attrVal);
        document.head.appendChild(el);
      }
      el.setAttribute('content', content);
    };

    // Meta Description
    setMetaTag('meta[name="description"]', 'name', 'description', seo.description);

    // Meta Keywords
    if (seo.keywords) {
      setMetaTag('meta[name="keywords"]', 'name', 'keywords', seo.keywords);
    }

    // OpenGraph Tags
    setMetaTag('meta[property="og:title"]', 'property', 'og:title', seo.title);
    setMetaTag('meta[property="og:description"]', 'property', 'og:description', seo.description);
    setMetaTag('meta[property="og:url"]', 'property', 'og:url', `https://nexatraders.io${currentPath}`);

    // Twitter Card Tags
    setMetaTag('meta[name="twitter:title"]', 'name', 'twitter:title', seo.title);
    setMetaTag('meta[name="twitter:description"]', 'name', 'twitter:description', seo.description);

    // Canonical Tag
    let canonical = document.querySelector('link[rel="canonical"]');
    if (!canonical) {
      canonical = document.createElement('link');
      canonical.setAttribute('rel', 'canonical');
      document.head.appendChild(canonical);
    }
    canonical.setAttribute('href', `https://nexatraders.io${currentPath}`);
  }, [location]);

  return null;
}
